### ISSUE TITLE
BUG: Logic checks if completion date field is missing

### ISSUE THREAD

**Issue by luketainton** [luketainton/roboluke-tasks#316]
Original reporter: @kmanwar89

Completion date field, if not filled in, will cause the task to bomb out. implement a check that validates the field is filled out, or set it as a required field somehow.

**Comment by luketainton** [comment]
@kmanwar89 I can't reproduce this, do you remember how we did it?

**Comment by kmanwar89** [comment]
I think it was simply creating a task via Roboluke and not setting anything in the date field (don't click anywhere in the date field in the Webex card, just enter a title/details and click submit)

Let me see if I can recreate it.

**Comment by kmanwar89** [comment]
Just tried to recreate - looks like some error detection is already in place as it prompts me to "complete all required fields"

Good to close I suppose?
